---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/**/*
- lib/**/*
- lib/*
- web_modules/**/*
- web_modules/*
- "lib/StringView.js"